---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
  env:
    ANSIBLE_GALAXY_DISPLAY_PROGRESS: "false"
driver:
  name: delegated
platforms:
  - name: opensuse-15-owncloud
    server_type: cx11
    image: 24146372
    from_snapshot: true
lint: |
  /usr/local/bin/flake8
provisioner:
  name: ansible
  env:
    ANSIBLE_FILTER_PLUGINS: ${ANSIBLE_FILTER_PLUGINS:-./plugins/filter}
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY:-./library}
verifier:
  name: testinfra
