---
kind: pipeline
name: linting
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - ansible-later
  image: thegeeklab/ansible-later
  name: later
- commands:
  - pip install -qq yapf
  - '[ -z "$(find .  -type f -name *.py)" ] || (yapf -rd ./)'
  environment:
    PY_COLORS: 1
  image: python:3.9
  name: python-format
- commands:
  - pip install -qq flake8
  - flake8
  environment:
    PY_COLORS: 1
  image: python:3.9
  name: python-flake8
trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
---
concurrency:
  limit: 1
depends_on:
- linting
kind: pipeline
name: testing-ubuntu1804
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - molecule test -s ubuntu1804
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root
  image: thegeeklab/molecule:3
  name: molecule
trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
workspace:
  base: /drone/src
  path: owncloud
---
concurrency:
  limit: 1
depends_on:
- linting
kind: pipeline
name: testing-ubuntu2004
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - molecule test -s ubuntu2004
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root
  image: thegeeklab/molecule:3
  name: molecule
trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
workspace:
  base: /drone/src
  path: owncloud
---
concurrency:
  limit: 1
depends_on:
- linting
kind: pipeline
name: testing-centos7
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - molecule test -s centos7
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root
  image: thegeeklab/molecule:3
  name: molecule
trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
workspace:
  base: /drone/src
  path: owncloud
---
concurrency:
  limit: 1
depends_on:
- linting
kind: pipeline
name: testing-centos8
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - molecule test -s centos8
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root
  image: thegeeklab/molecule:3
  name: molecule
trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
workspace:
  base: /drone/src
  path: owncloud
---
concurrency:
  limit: 1
depends_on:
- linting
kind: pipeline
name: testing-opensuse15
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - molecule test -s opensuse15
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root
  image: thegeeklab/molecule:3
  name: molecule
trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
workspace:
  base: /drone/src
  path: owncloud
---
depends_on:
- testing-ubuntu1804
- testing-ubuntu2004
- testing-centos7
- testing-centos8
- testing-opensuse15
kind: pipeline
name: release
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - git fetch -tq
  - git-chglog --no-color --no-emoji ${DRONE_TAG:---next-tag unreleased unreleased}
  - git-chglog --no-color --no-emoji -o CHANGELOG.md ${DRONE_TAG:---next-tag unreleased
    unreleased}
  image: thegeeklab/git-chglog
  name: changelog-generate
- image: plugins/github-release
  name: release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**
trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**
---
depends_on:
- release
kind: pipeline
name: documentation
platform:
  arch: amd64
  os: linux
steps:
- environment:
    ANSIBLE_DOCTOR_EXCLUDE_FILES: molecule/
    ANSIBLE_DOCTOR_FORCE_OVERWRITE: true
    ANSIBLE_DOCTOR_LOG_LEVEL: INFO
    ANSIBLE_DOCTOR_OUTPUT_DIR: _docs/
    ANSIBLE_DOCTOR_TEMPLATE: hugo-book
  image: thegeeklab/ansible-doctor
  name: generate
- image: plugins/gh-pages
  name: publish
  settings:
    pages_directory: _docs/
    password:
      from_secret: github_token
    target_branch: docs
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/master
- image: plugins/downstream
  name: trigger
  settings:
    fork: true
    repositories:
    - owncloud-ansible/owncloud-ansible.github.io@source
    server: https://drone.owncloud.com
    token:
      from_secret: drone_token
  when:
    ref:
    - refs/heads/master
trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
---
depends_on:
- documentation
kind: pipeline
name: notification
platform:
  arch: amd64
  os: linux
steps:
- image: plugins/slack:1
  name: notify
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private
trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure
---
kind: signature
hmac: ae31e032aec383019487fa74a430ad2d5d703393028a2487c80fdfd1dc933a15

...
