---
kind: pipeline
name: linting

platform:
  os: linux
  arch: amd64

steps:
  - name: later
    image: thegeeklab/ansible-later
    commands:
      - ansible-later

  - name: python-format
    image: python:3.9
    commands:
      - pip install -qq yapf
      - "[ -z \"$(find .  -type f -name *.py)\" ] || (yapf -rd ./)"
    environment:
      PY_COLORS: 1

  - name: python-flake8
    image: python:3.9
    commands:
      - pip install -qq flake8
      - flake8
    environment:
      PY_COLORS: 1

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
name: testing-ubuntu2004

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
  - name: molecule
    image: thegeeklab/molecule:3
    commands:
      - molecule test -s ubuntu2004
    environment:
      HCLOUD_TOKEN:
        from_secret: hcloud_token
      PY_COLORS: 1
      USER: root

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - linting

---
kind: pipeline
name: testing-centos7

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
  - name: molecule
    image: thegeeklab/molecule:3
    commands:
      - molecule test -s centos7
    environment:
      HCLOUD_TOKEN:
        from_secret: hcloud_token
      PY_COLORS: 1
      USER: root

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - linting

---
kind: pipeline
name: testing-rocky8

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
  - name: molecule
    image: thegeeklab/molecule:3
    commands:
      - molecule test -s rocky8
    environment:
      HCLOUD_TOKEN:
        from_secret: hcloud_token
      PY_COLORS: 1
      USER: root

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - linting

---
kind: pipeline
name: testing-opensuse15

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
  - name: molecule
    image: thegeeklab/molecule:3
    commands:
      - molecule test -s opensuse15
    environment:
      HCLOUD_TOKEN:
        from_secret: hcloud_token
      PY_COLORS: 1
      USER: root

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - linting

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
  - name: changelog-generate
    image: thegeeklab/git-chglog
    commands:
      - git fetch -tq
      - git-chglog --no-color --no-emoji ${DRONE_TAG:---next-tag unreleased unreleased}
      - git-chglog --no-color --no-emoji -o CHANGELOG.md ${DRONE_TAG:---next-tag unreleased unreleased}

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      note: CHANGELOG.md
      overwrite: true
      title: ${DRONE_TAG}
    when:
      ref:
        - refs/tags/**

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - testing-ubuntu2004
  - testing-centos7
  - testing-rocky8
  - testing-opensuse15

---
kind: pipeline
name: documentation

platform:
  os: linux
  arch: amd64

steps:
  - name: generate
    image: thegeeklab/ansible-doctor
    environment:
      ANSIBLE_DOCTOR_EXCLUDE_FILES: molecule/
      ANSIBLE_DOCTOR_FORCE_OVERWRITE: true
      ANSIBLE_DOCTOR_LOG_LEVEL: INFO
      ANSIBLE_DOCTOR_OUTPUT_DIR: _docs/
      ANSIBLE_DOCTOR_TEMPLATE: hugo-book

  - name: publish
    image: plugins/gh-pages
    settings:
      pages_directory: _docs/
      password:
        from_secret: github_token
      target_branch: docs
      username:
        from_secret: github_username
    when:
      ref:
        - refs/heads/main

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - release

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
  - name: notify
    image: plugins/slack:1
    settings:
      channel:
        from_secret: rocketchat_chat_channel
      webhook:
        from_secret: rocketchat_chat_webhook

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
  status:
    - success
    - failure

depends_on:
  - documentation

---
kind: signature
hmac: 70eca7631551a2f82a1ac54eeb1e948675423ac55513be6c48b05bf8f82a850e

...
