---
kind: pipeline
name: linting

platform:
  os: linux
  arch: amd64

steps:
- name: later
  image: thegeeklab/ansible-later
  commands:
  - ansible-later

- name: python-format
  image: python:3.9
  commands:
  - pip install -qq yapf
  - "[ -z \"$(find .  -type f -name *.py)\" ] || (yapf -rd ./)"
  environment:
    PY_COLORS: 1

- name: python-flake8
  image: python:3.9
  commands:
  - pip install -qq flake8
  - flake8
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: testing-ubuntu1804

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
- name: molecule
  image: thegeeklab/molecule:3
  commands:
  - molecule test -s ubuntu1804
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: testing-ubuntu2004

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
- name: molecule
  image: thegeeklab/molecule:3
  commands:
  - molecule test -s ubuntu2004
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: testing-centos7

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
- name: molecule
  image: thegeeklab/molecule:3
  commands:
  - molecule test -s centos7
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: testing-centos8

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
- name: molecule
  image: thegeeklab/molecule:3
  commands:
  - molecule test -s centos8
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: testing-opensuse15

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
- name: molecule
  image: thegeeklab/molecule:3
  commands:
  - molecule test -s opensuse15
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: documentation

platform:
  os: linux
  arch: amd64

steps:
- name: generate
  image: thegeeklab/ansible-doctor
  environment:
    ANSIBLE_DOCTOR_EXCLUDE_FILES: molecule/
    ANSIBLE_DOCTOR_FORCE_OVERWRITE: true
    ANSIBLE_DOCTOR_LOG_LEVEL: INFO
    ANSIBLE_DOCTOR_OUTPUT_DIR: _docs/
    ANSIBLE_DOCTOR_TEMPLATE: hugo-book

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: _docs/
    password:
      from_secret: github_token
    target_branch: docs
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/master

- name: trigger
  image: plugins/downstream
  settings:
    fork: true
    repositories:
    - owncloud-ansible/owncloud-ansible.github.io@source
    server: https://drone.owncloud.com
    token:
      from_secret: drone_token
  when:
    ref:
    - refs/heads/master

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- testing-ubuntu1804
- testing-ubuntu2004
- testing-centos7
- testing-centos8
- testing-opensuse15

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack:1
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- linting
- testing-ubuntu1804
- testing-ubuntu2004
- testing-centos7
- testing-centos8
- testing-opensuse15
- documentation

---
kind: signature
hmac: 565983c04fe78fbb8116e32bed9c877477cdec52503272a74448c537ce7f1e99

...
