---
kind: pipeline
name: linting

platform:
  os: linux
  arch: amd64

steps:
- name: later
  image: xoxys/ansible-later:latest
  commands:
  - ansible-later

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: testing-ubuntu1804

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
- name: molecule
  image: xoxys/molecule:hcloud-linux-amd64
  commands:
  - /bin/bash /docker-entrypoint.sh
  - molecule test -s ubuntu1804
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: testing-centos7

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

workspace:
  base: /drone/src
  path: owncloud

steps:
- name: molecule
  image: xoxys/molecule:hcloud-linux-amd64
  commands:
  - /bin/bash /docker-entrypoint.sh
  - molecule test -s centos7
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
    PY_COLORS: 1
    USER: root

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- linting

---
kind: pipeline
name: documentation

platform:
  os: linux
  arch: amd64

steps:
- name: generate
  image: xoxys/ansible-doctor:latest
  environment:
    ANSIBLE_DOCTOR_EXCLUDE_FILES: molecule/
    ANSIBLE_DOCTOR_FORCE_OVERWRITE: true
    ANSIBLE_DOCTOR_LOG_LEVEL: INFO
    ANSIBLE_DOCTOR_OUTPUT_DIR: _docs/
    ANSIBLE_DOCTOR_THEME: hugo

- name: publish
  image: plugins/gh-pages:latest
  settings:
    pages_directory: _docs/
    password:
      from_secret: github_token
    target_branch: docs
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/master

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- testing-ubuntu1804
- testing-centos7

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: docs
  image: plugins/downstream
  settings:
    fork: true
    repositories:
    - owncloud-ansible/owncloud-ansible.github.io@source
    server: https://drone.owncloud.com
    token:
      from_secret: drone_token
  when:
    ref:
    - refs/heads/docs

- name: notify
  image: plugins/slack:1
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private

trigger:
  ref:
  - refs/heads/master
  - refs/heads/docs
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- linting
- testing-ubuntu1804
- testing-centos7
- documentation

---
kind: signature
hmac: b9e89a7ca93642bd286ecd19bda52f393a57d79e7b17873207c6162783196ab1

...
