---
- name: Set misc core settings
  oc_config:
    name: "{{ item.name }}"
    attribute: "{{ item.attr }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ __occ_core_config }}"
  become: True
  become_user: "{{ owncloud_app_user }}"

- name: Set user env variable for crontab
  cron:
    name: USER
    env: True
    job: "{{ owncloud_app_user }}"
    user: "{{ owncloud_app_user }}"
    cron_file: owncloud
    state: "{{ 'present' if owncloud_cron_backend == 'cron' else 'absent' }}"

- name: Setup system background jobs
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    day: "{{ item.day | default('*') }}"
    month: "{{ item.month | default('*') }}"
    user: "{{ owncloud_app_user }}"
    job: "{{ item.job }}"
    cron_file: owncloud
    state: "{{ 'present' if owncloud_cron_backend == 'cron' else 'absent' }}"
  loop: "{{ owncloud_cron_jobs }}"
  loop_control:
    label: "{{ item.name }}"

- name: Get current htaccess rewrite state from .htaccess file
  command: "/bin/grep 'RewriteBase /' /var/www/owncloud/.htaccess"
  register: owncloud_register_htaccess_rewrite_check
  check_mode: no
  failed_when: "owncloud_register_htaccess_rewrite_check.rc == 2"
  changed_when: False
  become: True
  become_user: "{{ owncloud_app_user }}"

- name: Update htaccess rewrite rules
  command: "{{ owncloud_occ_executable | quote }} maintenance:update:htaccess"
  register: owncloud_register_occ_rewrite_htaccess_rules
  failed_when: "not '.htaccess has been updated' in owncloud_register_occ_rewrite_htaccess_rules.stdout"
  become: True
  become_user: "{{ owncloud_app_user }}"
  when: "(('RewriteBase /' in owncloud_register_htaccess_rewrite_check.stdout)|bool) != (owncloud_rewrite_base_enabled|bool)"

...
