---
- name: Ensure that Ansible local facts directory is present
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Save ownCloud local facts
  template:
    src: etc/ansible/facts.d/owncloud.fact.j2
    dest: /etc/ansible/facts.d/owncloud.fact
    owner: root
    group: root
    mode: 0755
  register: __owncloud_register_local_facts

- name: Gather facts if they were modified
  action: setup
  when: __owncloud_register_local_facts is changed

- name: Create system group '{{ owncloud_system_group }}'
  group:
    name: "{{ owncloud_system_group }}"
    state: present
    system: True

- name: Create system user '{{ owncloud_system_user }}'
  user:
    name: "{{ owncloud_system_user }}"
    group: "{{ owncloud_system_group }}"
    home: "{{ owncloud_system_user_home }}"
    comment: "{{ owncloud_system_user_comment }}"
    shell: "{{ owncloud_system_user_shell }}"
    system: True
    state: present

- name: Setup shortcut for the occ command
  template:
    src: usr/local/bin/occ.j2
    dest: "{{ owncloud_occ_executable }}"
    owner: root
    group: "{{ owncloud_system_group }}"
    mode: 0755

- name: Lookup occ binary shortcode
  stat:
    path: "{{ owncloud_occ_executable }}"
  register: __occ_bin_link

- name: Lookup occ source binary
  stat:
    path: "{{ owncloud_deploy_path }}/occ"
  register: __occ_bin_src

- name: Register current ownCloud version
  set_fact:
    owncloud_current_version: "{{ ansible_local.owncloud.version }}"

- name: Install dependencies
  loop: "{{ owncloud_packages_extra + __owncloud_packages }}"
  package:
    name: "{{ item }}"
    update_cache: "{{ owncloud_apt_cache_update }}"
    state: present

- name: Create ownCloud directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ owncloud_src_path }}", mode: "0750", owner: "{{ owncloud_app_user }}", group: "{{ owncloud_app_group }}" }
    - { path: "{{ owncloud_deploy_path }}", mode: "0750", owner: "{{ owncloud_app_user }}", group: "{{ owncloud_app_group }}" }
    - { path: "{{ owncloud_data_path }}", mode: "0770", owner: "{{ owncloud_app_user }}", group: "{{ owncloud_app_group }}" }
    - { path: "{{ __owncloud_custom_apps_path }}", mode: "0770", owner: "{{ owncloud_app_user }}", group: "{{ owncloud_app_group }}" }
    - { path: "{{ owncloud_config_path }}", mode: "0770", owner: "{{ owncloud_app_user }}", group: "{{ owncloud_app_group }}" }
  loop_control:
    label: "{{ item.path }}"

- name: Create custom temp directory (if defined)
  file:
    path: "{{ owncloud_temp_path }}"
    state: directory
    owner: "{{ owncloud_app_user }}"
    group: "{{ owncloud_app_group }}"
    mode: "0770"
  when:
    - owncloud_temp_path is defined
    - not owncloud_temp_path == '/tmp'
    - not owncloud_temp_path == '/var/tmp'

...
