---
- src: https://github.com/owncloud-ansible/mariadb 
  scm: git
  version: master

- src: https://github.com/owncloud-ansible/apache
  scm: git
  version: master

- src: https://github.com/owncloud-ansible/php
  scm: git
  version: master

- src: https://github.com/owncloud-ansible/redis
  scm: git
  version: master

...
