---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu-18.04-owncloud
    server_type: cx11
    image: ubuntu-18.04
lint: |
  flake8
provisioner:
  name: ansible
verifier:
  name: testinfra

