---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: centos-7-owncloud
    server_type: cx11
    image: centos-7
lint: |
  flake8
provisioner:
  name: ansible
verifier:
  name: testinfra